"""Provider contracts for AniBridge."""

from anibridge.provider.base import (
    Activity,
    BrowseableEntry,
    Collection,
    Entity,
    Entry,
    Media,
    Provider,
    Role,
    State,
    User,
)
from anibridge.provider.capabilities import (
    SupportsBackup,
    SupportsBrowse,
    SupportsDelete,
    SupportsDeriveState,
    SupportsGet,
    SupportsMappings,
    SupportsPut,
    SupportsSearch,
    SupportsWebhooks,
)
from anibridge.provider.types import (
    Key,
    Logger,
    MappingRef,
    ResolvedMapping,
    SerializedState,
    WebhookPayload,
    WebhookResult,
)

__all__ = [
    "Activity",
    "BrowseableEntry",
    "Collection",
    "Entity",
    "Entry",
    "Key",
    "Logger",
    "MappingRef",
    "Media",
    "Provider",
    "ResolvedMapping",
    "Role",
    "SerializedState",
    "State",
    "SupportsBackup",
    "SupportsBrowse",
    "SupportsDelete",
    "SupportsDeriveState",
    "SupportsGet",
    "SupportsMappings",
    "SupportsPut",
    "SupportsSearch",
    "SupportsWebhooks",
    "User",
    "WebhookPayload",
    "WebhookResult",
]
